research_task:
  description: >
    Conduct a thorough research about Electric Vehicle
    Make sure you find any research and company information given
    the current year is 2025 and last year 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant companies and research about Electriv Vehicles
  agent: researcher

reporting_task:
  description: >
    Review the research you got and expand each ones into a full section for a report including the who published it.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main research topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
